Algoritmo "AreaCirculo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Pedir o raio do círculo e calcular com pi a área desse círculo
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
raio:real
area:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa Área do Círculo")
Escreva("Escreva o raio: ")
leia(raio)
area<- pi*raio^2
Escreva("A área do círculo é: ",area)


Fimalgoritmo