Algoritmo "AreaTriangulo"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Pede a base do triângulo, sua altura e
//depois responde a área
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
base:real
altura:real
area:real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa Área Triângulo")
Escreva("Digite a base do triângulo ")
leia(base)
Escreva("Digite a altura do triângulo ")
leia(altura)
area<- (base*altura)/2
Escreva("A área do triângulo é: ",area)


Fimalgoritmo