Algoritmo "Exercicio51Faccat"
// Disciplina: Lógica de Programaçãocom JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Escreva um algoritmo para imprimir os números
//de 1 (inclusive) a 10 (inclusive) em ordem decrescente.
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 08/09/2026
Var
// Seção de Declarações das variáveis
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
Escreval("Ordem Decrescente do 10 a 1")
numero<-10
repita
Escreval(numero)
numero<- numero-1
até numero < 0

Fimalgoritmo