Algoritmo "Exercicio54Faccat"
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Escreva um algoritmo que calcule e
// imprima a tabuada do 8 (1 a 10).
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 09/09/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Tabuada do 8")
numero<-8
repita
Escreval(numero)
numero<- numero+8
até numero>80
Fimalgoritmo