Algoritmo "exercicio5Faccat"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exercício 5 - Pedir um número e mostrar seu antecessor
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro
antecessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval(" Programa Antecessor")
Escreval ("Digite um número")
leia(numero)
antecessor<-numero-1
Escreval("O antecessor é ",antecessor)

Fimalgoritmo