Algoritmo "exercicio12Faccat"
// 
//  Professor: Jailson Costa dos Santos
// Descrição   : Solicita valores em farenheit e converte para Celsius
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
farenheit:real
celsius:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("FarenheitCelsius")
Escreva("Digite o valor em Farenheit: ")
leia(farenheit)
celsius<-  (farenheit-32)/9*5
Escreva("O valor em Celsius é: ",celsius)


Fimalgoritmo