Algoritmo "FarenheitExercicio7aManzzano"
// 
// Professor: Jailson Costa dos Santos
// Descrição   : Solicitar o valor em Celsius para que o programa entregue
// o valor em Farenheit
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 02/09/2026
Var
// Seção de Declarações das variáveis 
temperaturaCelsius:real
temperaturaFarenheit:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Conversão de Temperatura ")
Escreva("Digite o valor em graus Celcius: ")
leia(temperaturaCelsius)
temperaturaFarenheit<- (9*temperaturaCelsius+160)/5
Escreva("A temperatura em Farenheit é: ",temperaturaFarenheit)
Fimalgoritmo