Algoritmo "L03A"
//  
//  
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa  dos Santos
// Descrição   : Apresentar os resultados de uma tabuada de
//multiplicar (de 1 até 10) de um número qualquer.
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 10/09/2026
Var
// Seção de Declarações das variáveis 
multiplicador: inteiro
numero:inteiro
contador: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Tabuada")
Escreval("Digite um número: ")
leia(numero)
contador<- 1
enquanto contador < 11 faca
multiplicador<- numero * contador
Escreval("O número ",numero," X ",contador, " = ",multiplicador )
contador<- contador + 1
fimenquanto
Fimalgoritmo