Algoritmo "L03B"
//  
//  
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa  dos Santos
// Descrição   : Apresentar o total da soma obtida dos cem primeiros
// números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 10/09/2026
Var
// Seção de Declarações das variáveis 
contador,somador:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Soma dos 100 primeiros números")
Escreval("")
enquanto contador < 100 faca
contador<- contador+1
Escreval("Enquanto o contador é: ",contador," o somador é: ",somador)
somador<- somador+contador
fimenquanto
Fimalgoritmo