Algoritmo "L05A"
//
//
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Apresentar os quadrados dos números
//inteiros de 15 a 200.
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 24/09/2026
Var
   // Seção de Declarações das variáveis
   contador:inteiro
   quadrado:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Programa Quadrado dos Números de 15 a 200")

   para contador de 15 ate 200  faca
      quadrado <- contador * contador
      Escreval("O número é: ",contador," e o seu quadrado é: ",quadrado)
   fimpara
   Escreval("O número final, 200, possui o quadrado no valor de: ",quadrado)

Fimalgoritmo