Algoritmo "MaiorMenorDez"
// 
// Professor:Jailson Costa dos Santos
// Descrição   : Recebe um numero e depois decide se é maior que dez ou
//menor que dez
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("MaiorMenorDez")
Escreva("Digite um número: ")
leia(numero)
se(numero<10)então
escreva("NÃO É MAIOR QUE 10!")
senão
escreva("É MAIOR QUE 10!")
fimse
Fimalgoritmo