Algoritmo "SaidadeDados"
// Disciplina   : [Lógica de Programação e Linguagem JavaScript]
// Professor   : Jaílson Costa dos Santos
// Descrição   : Sáida de Dados
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Equipe 2 é a melhor!")

Fimalgoritmo