Algoritmo "Sistema Bancário"
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Um Sistema Bancário
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 09/09/2026
Var
// Seção de Declarações das variáveis 
agencia,senha,conta,opcao,outrasOpcoes:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("******************************************************")
Escreva("******************************************************")
Escreva("******************SISTEMA BANCÁRIO********************")
Escreva("******************************************************")
Escreva("*********************Equipe 02************************")
Escreva("******************************************************")
Escreva("************BEM-VINDO AO SISTEMA BANCÁRIO*************")
Escreva("******************************************************")
Escreval("Digite o número da sua conta: ")
leia(conta)
Escreval("Digite o número da sua agência: ")
leia(agencia)
Escreval("Digite a senha: ")
leia(senha)
se (conta=1234) e (agencia=4321) e (senha=29062006) então
Escreval(" Bem-Vindo")
Escreva(" Escolha A Opção Desejada")
Escreval("1- ")



Fimalgoritmo