Algoritmo "AreaLosango"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita o número da Diagonal Maior e Diagonal Menor, divide por 2 e entrega a área
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
dmenor:real
dmaior:real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa Área Losango")
Escreva("Digite a diagonal maior: ")
leia(dmaior)
Escreva("Digite a diagonal menor: ")
leia(dmenor)
area<-(dmaior*dmenor)/2
Escreva("A área do losango é: ",area)


Fimalgoritmo