Algoritmo "AreaQuadrado"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Pede a medida do lado do quadrado e já calcula a sua área
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
lado:real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa Área Quadrado")
Escreva("Digite o número do lado do quadrado: ")
leia(lado)
area<- lado^2
Escreva("A área do quadrado é ",area)

Fimalgoritmo