Algoritmo "Concatenacao"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Aprendendo Concatenação
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
nome:caracter
hobbie:caracter


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc.
escreva("Digite seu nome: ")
leia(nome)
escreva("Seu nome é  ",nome)


Fimalgoritmo