Algoritmo "Divisao"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita o primeiro e segundo número e divide ambos
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero1:inteiro
numero2:inteiro
divisao:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Multiplicação")
Escreva("Digite o primeiro número ")
leia(numero1)
Escreva("Digite o segundo número ")
leia(numero2)
divisao<-numero1\numero2
Escreva("O resultado é ",divisao)

Fimalgoritmo