Algoritmo "Exercicio52Faccat"
// Disciplina: Lógica de Programaçãocom JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Ler um valor N e imprimir todos os valores inteiros entre 1 (inclusive) e N (inclusive). Considere
//que o N será sempre maior que ZERO.
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 08/09/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Imprimir Valores Entre Inteiros e Um valor N")
Escreva("Digite um número ")

Fimalgoritmo