Algoritmo "Exercicio50Faccat"
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Escreva um algoritmo para imprimir os números de 1
//(inclusive) a 10 (inclusive) em ordem crescente.
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 08/09/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Contador de 1 a 10")
Escreva("Digite um número inteiro: ")
leia(numero)
repita
Escreval(numero)
numero<- numero + 1
até(numero >10)
Fimalgoritmo