Algoritmo "Exercicio27Faccat"

// Professor: Jailson Costa dos Santos
// Descrição   : Ler um valor e escrever se é positivo, negativo ou zero.
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 02/09/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval(" Número Positivo, Negativo ou Igual a Zero")
Escreva("Digite um número: ")
leia(numero)
se(numero>0) então
Escreva("O número digitado é positivo")
senão
se(numero=0) então
Escreva("O número digitado é igual a zero")
senão
Escreva("O número digitado é negativo")
fimse
fimse
Fimalgoritmo