Algoritmo "exercicio6Faccat"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exercício 6 - Solicitar medidas de altura e base de rentâgulo, calcular área e mostrar essa área
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
base:real
altura:real
area:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Área de Retângulo")
Escreva("Digite a altura do retângulo ")
leia(altura)
Escreva("Agora digite a base do retângulo ")
leia(base)
area<-base*altura
Escreva("A área do retângulo é: ",area," metros quadrados")

Fimalgoritmo