Algoritmo "L03E"
//  
//  
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Apresentar os resultados das potências de 3,
//variando do expoente 0 até o expoente 15. Deve ser considerado
//que qualquer número elevado a zero é 1, e elevado a 1 é ele
//próprio. Observe que neste exercício não pode ser utilizado o
//operador de exponenciação do portuguol (^).
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 11/09/2026
Var
// Seção de Declarações das variáveis 
potencia:inteiro
contador:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("As Potências de 3")
Escreva("")
potencia<- 1
enquanto contador < 15 faca
Escreval(potencia)
potencia<- potencia*3
contador<- contador+1
fimenquanto
Fimalgoritmo