Algoritmo "L05B"
//
//
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Apresentar os resultados de uma tabuada de
//multiplicar (de 1 até 10) de um número qualquer.
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 24/09/2026
Var
   // Seção de Declarações das variáveis
   numero:inteiro
   contador:inteiro
   multiplicacao:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Programa Tabuada")
   contador <- 1
   Escreval("Digite um número para ser mostrado sua tabuada")
   leia(numero)
   para contador de 1 ate 10 faca
      multiplicacao <- numero * contador
      Escreval("Número ",contador," x ",numero," = ",multiplicacao)
   fimpara
Fimalgoritmo