Algoritmo "L05C"
//
//
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Apresentar o total da soma obtida dos
//cem primeiros números inteiros (1+2+3+4+...+98+99+100).
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 24/09/2026
Var
   // Seção de Declarações das variáveis
   contador:inteiro
   somadora:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Programa Soma de 1 a 100")

   somadora <- 0
   para contador de 1 ate 100 faca
      somadora <- somadora + contador
      Escreval("O número está em ",contador," e a soma está em ",somadora)
   fimpara
   Escreval("A soma total é: ",somadora)

Fimalgoritmo