Algoritmo "L05E"
//
//
// Disciplina: Lógica de Programação com JavaScript
// Professor: Jailson Costa dos Santos
// Descrição   : Apresentar todos os valores numéricos inteiros
//ímpares situados na faixa de 0 a 20. Para verificar se o número é
//ímpar, efetuar dentro da malha a verificação lógica desta condição
//com a instrução se, perguntando se o número é ímpar; sendo,
//mostre-o; não sendo, passe para o próximo passo.
// Autor(a)    : Ana Paula Santos da Silva
// Data atual  : 24/09/2026
Var
   // Seção de Declarações das variáveis
   contador:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Programa Números Ímpares Entre 0 e 20")

   para contador de 0 ate 20 faca
      se contador % 2 <> 0 entao
         Escreval("Os números ímpares são: ",contador)

      senao
         Escreval("O número dessa posição não é par")
      fimse
      
   fimpara


Fimalgoritmo