Algoritmo "mutiplicacao"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita o primeiro e segundo número e depois multiplica-os
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero01:inteiro
numero02:inteiro
multiplica:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Multiplicação")
Escreval("Digite o primeiro número ")
leia(numero01)
Escreval("Digite o segundo número ")
leia(numero02)
multiplica<-numero01*numero02
Escreval("O resultado é: ",multiplica)

Fimalgoritmo