Algoritmo "PositivoNegativo"
// 
// Professor: Jailson Costa dos Santos
// Descrição   : Pede um numero e ler um valor e escrever se é positivo ou negativo
//(considere o valor zero como positivo).
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/09/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("PositivoNegativo")
Escreva("Digite um número: ")
leia(numero)
se(numero<0) então
Escreva("Esse número é negativo")
senão
Escreva("Esse número é positivo")
fimse
Fimalgoritmo