Algoritmo "Somar"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicitar dois números e posteriormente somá-los.
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero01:inteiro
numero02:inteiro
soma:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Por favor, digite o primeiro número ")
leia(numero01)
Escreval("Agora digite o segundo número ")
leia(numero02)
soma<-numero01+numero02
Escreva("A soma é: ",soma)


Fimalgoritmo