Algoritmo "Subtracao"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Solicita dois números e subtrai eles posteriormente
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero01:inteiro
numero02:inteiro
subtracao:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Digite o primeiro número: ")
leia(numero01)
Escreval("Digite o segundo número:  ")
leia(numero02)
subtracao<- numero01-numero02
Escreva("A subtração dos dois números é ",subtracao)


Fimalgoritmo