Algoritmo "Sucessor"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Exercício 6 - Pede um número e entrega seu sucessor
// Autor(a)    : Ana Paula
// Data atual  : 28/08/2026
Var
// Seção de Declarações das variáveis 
numero:inteiro
sucessor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Sucessor")
Escreval("Digite um número ")
leia(numero)
sucessor<-numero+1
Escreva("O sucessor é  ",sucessor)

Fimalgoritmo