Algoritmo "ValorAeB"
// 
//  
//Descrição   : Exercício 1, algoritmo que armazene o número 10 na variável
//A e 20 na variável B e depois que troquem o valor entre si
// Autor(a)    : Ana Paula
// Data atual  : 30/08/2026
Var
// Seção de Declarações das variáveis 
a:inteiro
b:inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreval("Programa ValorAeB ")
Escreval (" A variável 'A' recebe o número 10 e a variável 'B' recebe 20")
a<-10
b<-20

Escreval ("Vou trocar os valores entre as variáveis 'A' e 'B'")
a<- b
b<- a
Escreval("Agora vou chamar a variável 'A' cujo valor é:",a)
Escreval("Agora vou chamar a variável 'B' cujo valor é:",b)

Fimalgoritmo